version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.11.0

jobs:
  build-and-test-and-deploy:
    <<: *defaults
    docker:
      - image: cibuilds/github:0.10
    steps:
    - checkout
    - run: npm install
    - run: npm run build
    - run: tar czf static_website.tar.gz -C public .
    - store_artifacts:
        path: static_website.tar.gz

    # Trigger a new build of the deploy project
    - run: "curl -X POST --header \"Content-Type: application/json\" https://circleci.com/api/v1.1/project/github/PokeAPI/deploy/build?circle-token=$CIRCLECI_API_TOKEN"
    - attach_workspace:
        at: ./public
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=$(git rev-parse HEAD)
          ghr -t ${GITHUB_TOKEN_ISSUED_BY_NARAMSIM} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./static_website.tar.gz

workflows:
  version: 2

  commit:
    jobs:
      - build-and-test-and-deploy
          # filters:
          #   branches:
          #     only: master
